// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrvK82SvYxPx9zW_Oycxts5octzLSki9c',
    appId: '1:414643737187:web:8d0fc20d14c1c4af299e56',
    messagingSenderId: '414643737187',
    projectId: 'community-food-app',
    authDomain: 'community-food-app.firebaseapp.com',
    storageBucket: 'community-food-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIQQgdqA__1Msej0q52TuJ8fal_t8qN6M',
    appId: '1:414643737187:android:e8a1a6893ad5b80f299e56',
    messagingSenderId: '414643737187',
    projectId: 'community-food-app',
    storageBucket: 'community-food-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvHikOk4-zqljQ1TGsDyNx0DkNqF0Q9DM',
    appId: '1:414643737187:ios:b1178fbf15af0add299e56',
    messagingSenderId: '414643737187',
    projectId: 'community-food-app',
    storageBucket: 'community-food-app.appspot.com',
    iosBundleId: 'com.example.communityFoodApp',
  );
}
